### ISSUE TITLE
Compiling on a Mac with OpenSSL installed via Homebrew

### ISSUE THREAD

**Issue by l3nz** [elixir-webrtc/ex_dtls#46]
It may be worthwhile adding to the README that for a Mac you might need to set 

     export PKG_CONFIG_PATH=/opt/homebrew/Cellar/openssl@3/3.1.0/lib/pkgconfig
    
To avoid `Package openssl was not found in the pkg-config search path.`

It may save a bit of time to someone else, so I'm posting it.

**Comment by mickel8** [comment]
Hi @l3nz, thanks!

Do you have ARM? We didn't notice the need for this extra export :thinking:

**Comment by mickel8** [comment]
In our case, pkgconfig was always searchable

**Comment by l3nz** [comment]
Yes it's ARM, but I think that the main deal is that you have no idea how OpenSSL is installed. I guess most people would use brew, but it's a guess.
